# .readthedocs.yml

version: 2

python:
   version: 3.6
   install:
      - requirements: docs/requirements.txt
      - method: setuptools
        path: .
   system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py


formats:
    - epub
    - pdf